In [72]:
import pandas as pd
import numpy as np

In [73]:
pd.set_option('display.max_columns', None)

In [74]:
df = pd.read_csv(r"C:\Users\Chota Don\Documents\Customer Churn\WA_Fn-UseC_-Telco-Customer-Churn.csv")

In [75]:
print("First 5 Rows:")
display(df.head())

First 5 Rows:

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [76]:
print("\nShape:")
print(df.shape)

Shape:
(7043, 21)

In [77]:
print("\nColumn Names:")
print(df.columns.tolist())

Column Names:
['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn']

In [78]:
print("\nDataset Information:")
df.info()

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB

In [79]:
print("\nMissing Values:")
print(df.isnull().sum())

Missing Values:
customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [80]:
print("\nDataset Overview:")
display(df.describe())

Dataset Overview:

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [81]:
print("\nCategorical Summary:")
display(df.describe(include='object'))

Categorical Summary:

C:\Users\Chota Don\AppData\Local\Temp\ipykernel_16500\3745775991.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  display(df.describe(include='object'))

,customerID,gender,Partner,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,TotalCharges,Churn
count,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043
unique,7043,2,2,2,2,3,3,3,3,3,3,3,3,3,2,4,6531,2
top,7590-VHVEG,Male,No,No,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,20.2,No
freq,1,3555,3641,4933,6361,3390,3096,3498,3088,3095,3473,2810,2785,3875,4171,2365,11,5174

In [82]:
print("\nTarget Variable Distribution:")
print(df["Churn"].value_counts())

Target Variable Distribution:
Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [83]:
print("\nTarget Variable Percentage:")
print(df["Churn"].value_counts(normalize=True) * 100)

Target Variable Percentage:
Churn
No     73.463013
Yes    26.536987
Name: proportion, dtype: float64

In [84]:
print(df.duplicated().sum())

0

In [85]:
print("\nData Types:")
display(df.dtypes)

Data Types:

customerID              str
gender                  str
SeniorCitizen         int64
Partner                 str
Dependents              str
tenure                int64
PhoneService            str
MultipleLines           str
InternetService         str
OnlineSecurity          str
OnlineBackup            str
DeviceProtection        str
TechSupport             str
StreamingTV             str
StreamingMovies         str
Contract                str
PaperlessBilling        str
PaymentMethod           str
MonthlyCharges      float64
TotalCharges            str
Churn                   str
dtype: object

In [86]:
print("\nUnique Values:\n")

categorical_cols = df.select_dtypes(include='object').columns

for col in categorical_cols:
    print(f"{col}:")
    print(df[col].unique())
    print("-" * 60)

Unique Values:

customerID:
<StringArray>
['7590-VHVEG', '5575-GNVDE', '3668-QPYBK', '7795-CFOCW', '9237-HQITU',
 '9305-CDSKC', '1452-KIOVK', '6713-OKOMC', '7892-POOKP', '6388-TABGU',
 ...
 '9767-FFLEM', '0639-TSIQW', '8456-QDAVC', '7750-EYXWZ', '2569-WGERO',
 '6840-RESVB', '2234-XADUH', '4801-JZAZL', '8361-LTMKD', '3186-AJIEK']
Length: 7043, dtype: str
------------------------------------------------------------
gender:
<StringArray>
['Female', 'Male']
Length: 2, dtype: str
------------------------------------------------------------
Partner:
<StringArray>
['Yes', 'No']
Length: 2, dtype: str
------------------------------------------------------------
Dependents:
<StringArray>
['No', 'Yes']
Length: 2, dtype: str
------------------------------------------------------------
PhoneService:
<StringArray>
['No', 'Yes']
Length: 2, dtype: str
------------------------------------------------------------
MultipleLines:
<StringArray>
['No phone service', 'No', 'Yes']
Length: 3, dtype: str
------------------------------------------------------------
InternetService:
<StringArray>
['DSL', 'Fiber optic', 'No']
Length: 3, dtype: str
------------------------------------------------------------
OnlineSecurity:
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
------------------------------------------------------------
OnlineBackup:
<StringArray>
['Yes', 'No', 'No internet service']
Length: 3, dtype: str
------------------------------------------------------------
DeviceProtection:
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
------------------------------------------------------------
TechSupport:
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
------------------------------------------------------------
StreamingTV:
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
------------------------------------------------------------
StreamingMovies:
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
------------------------------------------------------------
Contract:
<StringArray>
['Month-to-month', 'One year', 'Two year']
Length: 3, dtype: str
------------------------------------------------------------
PaperlessBilling:
<StringArray>
['Yes', 'No']
Length: 2, dtype: str
------------------------------------------------------------
PaymentMethod:
<StringArray>
[         'Electronic check',              'Mailed check',
 'Bank transfer (automatic)',   'Credit card (automatic)']
Length: 4, dtype: str
------------------------------------------------------------
TotalCharges:
<StringArray>
[  '29.85',  '1889.5',  '108.15', '1840.75',  '151.65',   '820.5',  '1949.4',
   '301.9', '3046.05', '3487.95',
 ...
 '2625.25', '6886.25',  '1495.1',   '743.3',  '1419.4',  '1990.5',  '7362.9',
  '346.45',   '306.6',  '6844.5']
Length: 6531, dtype: str
------------------------------------------------------------
Churn:
<StringArray>
['No', 'Yes']
Length: 2, dtype: str
------------------------------------------------------------

C:\Users\Chota Don\AppData\Local\Temp\ipykernel_16500\1630894641.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include='object').columns

Data Preprocessing

In [87]:
df_ml = df.copy()

In [88]:
df_ml.drop("customerID", axis=1, inplace=True)

In [89]:
df_ml["TotalCharges"] = pd.to_numeric(
    df_ml["TotalCharges"],
    errors="coerce"
)

df_ml["TotalCharges"] = df_ml["TotalCharges"].fillna(
    df_ml["TotalCharges"].median()
)

In [90]:
print("Missing Values:")
print(df_ml.isnull().sum())

Missing Values:
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [91]:
df_ml["TotalCharges"].fillna(df_ml["TotalCharges"].median(), inplace=True)

C:\Users\Chota Don\AppData\Local\Temp\ipykernel_16500\3385868969.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df_ml["TotalCharges"].fillna(df_ml["TotalCharges"].median(), inplace=True)

0         29.85
1       1889.50
2        108.15
3       1840.75
4        151.65
         ...
7038    1990.50
7039    7362.90
7040     346.45
7041     306.60
7042    6844.50
Name: TotalCharges, Length: 7043, dtype: float64

In [92]:
df_ml["Churn"] = df_ml["Churn"].map({"No": 0, "Yes": 1})

In [93]:
df_ml = pd.get_dummies(df_ml, drop_first=True)

In [94]:
X = df_ml.drop("Churn", axis=1)
y = df_ml["Churn"]

In [95]:
print("\nFeature Matrix Shape:", X.shape)
print("Target Shape:", y.shape)

Feature Matrix Shape: (7043, 30)
Target Shape: (7043,)

In [96]:
df_ml["TotalCharges"] = pd.to_numeric(df_ml["TotalCharges"], errors="coerce")

df_ml["TotalCharges"] = df_ml["TotalCharges"].fillna(df_ml["TotalCharges"].median())

In [97]:
print(df_ml.isnull().sum())

SeniorCitizen                            0
tenure                                   0
MonthlyCharges                           0
TotalCharges                             0
Churn                                    0
gender_Male                              0
Partner_Yes                              0
Dependents_Yes                           0
PhoneService_Yes                         0
MultipleLines_No phone service           0
MultipleLines_Yes                        0
InternetService_Fiber optic              0
InternetService_No                       0
OnlineSecurity_No internet service       0
OnlineSecurity_Yes                       0
OnlineBackup_No internet service         0
OnlineBackup_Yes                         0
DeviceProtection_No internet service     0
DeviceProtection_Yes                     0
TechSupport_No internet service          0
TechSupport_Yes                          0
StreamingTV_No internet service          0
StreamingTV_Yes                          0
StreamingMovies_No internet service      0
StreamingMovies_Yes                      0
Contract_One year                        0
Contract_Two year                        0
PaperlessBilling_Yes                     0
PaymentMethod_Credit card (automatic)    0
PaymentMethod_Electronic check           0
PaymentMethod_Mailed check               0
dtype: int64

In [98]:
display(df_ml.head())

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,Churn,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,InternetService_Fiber optic,InternetService_No,OnlineSecurity_No internet service,OnlineSecurity_Yes,OnlineBackup_No internet service,OnlineBackup_Yes,DeviceProtection_No internet service,DeviceProtection_Yes,TechSupport_No internet service,TechSupport_Yes,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,29.85,29.85,0,False,True,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,True,False
1,0,34,56.95,1889.50,0,True,False,False,True,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,True
2,0,2,53.85,108.15,1,True,False,False,True,False,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,True
3,0,45,42.30,1840.75,0,True,False,False,False,True,False,False,False,False,True,False,False,False,True,False,True,False,False,False,False,True,False,False,False,False,False
4,0,2,70.70,151.65,1,False,False,False,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False

Train-Test Split & Model Training

In [105]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

In [100]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20,random_state=42,stratify=y)

In [101]:
print("Training Features Shape :", X_train.shape)
print("Testing Features Shape  :", X_test.shape)
print("Training Target Shape   :", y_train.shape)
print("Testing Target Shape    :", y_test.shape)

Training Features Shape : (5634, 30)
Testing Features Shape  : (1409, 30)
Training Target Shape   : (5634,)
Testing Target Shape    : (1409,)

In [108]:
logistic_model = LogisticRegression(max_iter=1000)

logistic_model.fit(X_train,y_train)

logistic_predictions = logistic_model.predict(X_test)

c:\Users\Chota Don\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [104]:
print("Missing values in X_train:")
print(X_train.isnull().sum()[X_train.isnull().sum() > 0])

print("\nTotal missing values:")
print(X_train.isnull().sum().sum())

Missing values in X_train:
Series([], dtype: int64)

Total missing values:
0

In [109]:
logistic_accuracy = accuracy_score(y_test,logistic_predictions)

logistic_precision = precision_score(y_test,logistic_predictions)

logistic_recall = recall_score(y_test,logistic_predictions)

logistic_f1 = f1_score(y_test,logistic_predictions)

In [110]:
print("Accuracy:", logistic_accuracy)
print("Precision:", logistic_precision)
print("Recall:", logistic_recall)
print("F1 Score:", logistic_f1)

Accuracy: 0.8041163946061036
Precision: 0.6550632911392406
Recall: 0.553475935828877
F1 Score: 0.6

In [111]:
print("\nClassification Report:")
print(classification_report(y_test,logistic_predictions))

Classification Report:
              precision    recall  f1-score   support

           0       0.85      0.89      0.87      1035
           1       0.66      0.55      0.60       374

    accuracy                           0.80      1409
   macro avg       0.75      0.72      0.74      1409
weighted avg       0.80      0.80      0.80      1409

Decision Tree Model

In [112]:
tree_model = DecisionTreeClassifier(random_state=42)

In [113]:
tree_model.fit(X_train,y_train)

DecisionTreeClassifier(random_state=42)

In [114]:
tree_predictions = tree_model.predict(X_test)

In [117]:
tree_accuracy = accuracy_score(y_test,tree_predictions)

In [118]:
tree_precision = precision_score(y_test,tree_predictions)

In [119]:
tree_recall = recall_score(y_test,tree_predictions)

In [120]:
tree_f1 = f1_score(y_test,tree_predictions)

In [121]:
print("Accuracy:", tree_accuracy)
print("Precision:", tree_precision)
print("Recall:", tree_recall)
print("F1 Score:", tree_f1)

Accuracy: 0.7416607523066004
Precision: 0.5138888888888888
Recall: 0.4946524064171123
F1 Score: 0.5040871934604905

In [122]:
print("\nClassification Report:")
print(
    classification_report(
        y_test,
        tree_predictions
    )
)

Classification Report:
              precision    recall  f1-score   support

           0       0.82      0.83      0.83      1035
           1       0.51      0.49      0.50       374

    accuracy                           0.74      1409
   macro avg       0.67      0.66      0.66      1409
weighted avg       0.74      0.74      0.74      1409

In [123]:
comparison = pd.DataFrame(
    {"Model": ["Logistic Regression","Decision Tree"],
        "Accuracy": [logistic_accuracy,tree_accuracy],
        "Precision": [logistic_precision,tree_precision],
        "Recall": [logistic_recall,tree_recall],
        "F1 Score": [logistic_f1,tree_f1]
    }
)

In [124]:
display(comparison)

                 Model  Accuracy  Precision    Recall  F1 Score
0  Logistic Regression  0.804116   0.655063  0.553476  0.600000
1        Decision Tree  0.741661   0.513889  0.494652  0.504087

In [126]:
best_model = comparison.loc[comparison["F1 Score"].idxmax()]

print("\nBest Performing Model:")
print(best_model)

Best Performing Model:
Model        Logistic Regression
Accuracy                0.804116
Precision               0.655063
Recall                  0.553476
F1 Score                     0.6
Name: 0, dtype: object